name: 'Common Setup'
description: 'Setup repositories and pull image'
inputs:
  container:
    required: true
    description: 'the container to pull'
outputs: {}
runs:
    using: "composite"
    steps:
    - uses: actions/checkout@v2
      with:
        repository: pymor/pymor-deal.II
        submodules: true
        path: pymor-deal.II
    - name: pull image
      run: docker pull ${{ inputs.container }}
      shell: bash
