name: Building

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: mor-coupling
    - uses: actions/checkout@v2
      with:
        repository: pymor/pymor-deal.II
        submodules: true
        path: pymor-deal.II
    - name: setup
      run: |
         command="sudo apt-get -qy update && \
                  wget https://github.com/precice/precice/releases/download/v2.1.1/libprecice2_2.1.1_focal.deb && \
                    sudo apt-get -qy install ./libprecice2_2.1.1_focal.deb python3-pip python-is-python3 && \
                  pip install -q pymor~=2021.1 && \
                  cd /src/pymor-deal.II && \
                  pip install . && \
                  cd /src/mor-coupling && \
                  cmake . && \
                  make";

         echo $command

         docker pull dealii/dealii:v9.2.0-focal
         # need to set uid to allow container user to write to the mount
         docker run -t --user 0 -v $PWD:/src dealii/dealii:v9.2.0-focal /bin/sh -c "$command";
