name: Building

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  deal_image:
    timeout-minutes: 15
    strategy:
      matrix:
        container: ["dealii/dealii:v9.2.0-focal", "dealii/dealii:v9.3.0-focal"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # needed to have the local action avail.
      with:
        submodules: true
        path: mor-coupling
    - uses: ./mor-coupling/.github/actions/common_setup
      with:
        container: ${{ matrix.container }}
    - name: build
      run: |
         # need to set uid to allow container user to write to the mount
         docker run -t --user 0 -v $PWD:/src ${{ matrix.container }} /src/mor-coupling/.github/workflows/run_deal.ii.bash;
  pymor_image:
    timeout-minutes: 15
    strategy:
      matrix:
        container: ["zivgitlab.wwu.io/pymor/docker/pymor/testing_py3.9:ef38304121ce0de0cf414036094b19c443ad16e2",
          "zivgitlab.wwu.io/pymor/docker/pymor/testing_py3.7:ef38304121ce0de0cf414036094b19c443ad16e2"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # needed to have the local action avail.
      with:
        submodules: true
        path: mor-coupling
    - uses: ./mor-coupling/.github/actions/common_setup
      with:
        container: ${{ matrix.container }}
    - name: build
      run: |
         # need to set uid to allow container user to write to the mount
         docker run -t -e LOCAL_USER_ID=0 -v $PWD:/src ${{ matrix.container }} /src/mor-coupling/.github/workflows/run_pymor.bash
